# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8dc552ab3e453974d584a5fec9233aef019fc3d9a410b04b03da7831d5ef7deec907c0c08c759e4920427601edad4c06ce972649dac27b0deb130c4a0b4fd86c

test:
  secret_key_base: ee3c8ed229bf4540c4c96bff7e741480585ccaaa1f342a679f15fa99b76cc2ee90979d5e5469e5fb6854526b5b18bd92bdcd94133c53d7a4bba2e268ac34c9f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
